development:
 docker_call:
  "docker run -ti -e HOST_USER_ID=$(id -u) -e HOST_USER_GID=$(id -g) --rm -v /data/asap:/data/asap asap_run"
 server_url:
  https://asap.epfl.ch
 data_dir:
  /data
 user_data_dir:
  /data/users
 upload_data_dir:
  /data/uploads

production:
 docker_call:
  "docker run -ti -e HOST_USER_ID=$(id -u) -e HOST_USER_GID=$(id -g) --rm -v /data/asap:/data/asap asap_run"
 server_url:
  https://asap.epfl.ch
 data_dir:
  /data
 user_data_dir:
  /data/users
 upload_data_dir:
  /data/uploads
