---

development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

data:
  <<: *default

data_v4:
  <<: *default

data_v5:
  <<: *default

data_v6:
  <<: *default